version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: cse-db
    networks:
      - cse-network
    environment:
      POSTGRES_DB: cse-db
      POSTGRES_USER: cse
      POSTGRES_PASSWORD: lIi40we8nNf3eFe
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  cse-spring:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: cse-app
    networks:
      - cse-network
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
    cse-network:
        driver: bridge
